# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug_protocol.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x64\x65\x62ug_protocol.proto\"\xab\x01\n\x03\x43md\"\\\n\x04\x43ode\x12\x08\n\x04Mode\x10\x00\x12\x08\n\x04Peek\x10\x01\x12\x08\n\x04Poke\x10\x02\x12\x0b\n\x07\x43onsole\x10\x03\x12\x0c\n\x08Variable\x10\x04\x12\t\n\x05Trace\x10\x05\x12\x10\n\x0c\x45\x65promAccess\x10\x06\"\"\n\x0bSpecialChar\x12\x08\n\x03\x45sc\x10\xf1\x01\x12\t\n\x04Term\x10\xf2\x01\"\"\n\x04\x42\x61se\x12\x0c\n\x04\x44MA1\x10\x80\x80\x88\x80\x04\x12\x0c\n\x04\x44MA2\x10\x80\x88\x88\x80\x04\"\xa1\x01\n\x05\x45rror\"\x97\x01\n\x04\x43ode\x12\x08\n\x04None\x10\x00\x12\x0c\n\x08\x43rcError\x10\x01\x12\x12\n\x0eUnknownCommand\x10\x02\x12\x0f\n\x0bMissingData\x10\x03\x12\x0c\n\x08NoMemory\x10\x04\x12\x11\n\rInternalError\x10\x05\x12\x13\n\x0fUnknownVariable\x10\x06\x12\x0f\n\x0bInvalidData\x10\x07\x12\x0b\n\x07Timeout\x10\x08\"\x9d\x01\n\x08TraceCmd\x12\x17\n\x0cMaxTraceVars\x18\x01 \x01(\r:\x01\x34\"x\n\x06Subcmd\x12\t\n\x05\x46lush\x10\x00\x12\x0c\n\x08\x44ownload\x10\x01\x12\t\n\x05Start\x10\x02\x12\x0c\n\x08GetVarId\x10\x03\x12\x0c\n\x08SetVarId\x10\x04\x12\r\n\tGetPeriod\x10\x05\x12\r\n\tSetPeriod\x10\x06\x12\x10\n\x0c\x43ountSamples\x10\x07\"B\n\tVarAccess\"5\n\x06Subcmd\x12\x0b\n\x07GetInfo\x10\x00\x12\x07\n\x03Get\x10\x01\x12\x07\n\x03Set\x10\x02\x12\x0c\n\x08GetCount\x10\x03\"*\n\tEepromCmd\"\x1d\n\x06Subcmd\x12\x08\n\x04Read\x10\x00\x12\t\n\x05Write\x10\x01\"V\n\x03Var\"(\n\x04Type\x12\t\n\x05Int32\x10\x01\x12\n\n\x06UInt32\x10\x02\x12\t\n\x05\x46loat\x10\x03\"%\n\x06\x41\x63\x63\x65ss\x12\x0c\n\x08ReadOnly\x10\x00\x12\r\n\tReadWrite\x10\x01\"-\n\rControllerDbg\"\x1c\n\x04Mode\x12\n\n\x06Normal\x10\x00\x12\x08\n\x04\x42oot\x10\x01')
)



_CMD_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Cmd.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Mode', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Peek', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Poke', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Console', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Variable', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Trace', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EepromAccess', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_CMD_CODE)

_CMD_SPECIALCHAR = _descriptor.EnumDescriptor(
  name='SpecialChar',
  full_name='Cmd.SpecialChar',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Esc', index=0, number=241,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Term', index=1, number=242,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=126,
  serialized_end=160,
)
_sym_db.RegisterEnumDescriptor(_CMD_SPECIALCHAR)

_CMD_BASE = _descriptor.EnumDescriptor(
  name='Base',
  full_name='Cmd.Base',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DMA1', index=0, number=1073872896,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DMA2', index=1, number=1073873920,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_CMD_BASE)

_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Error.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CrcError', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnknownCommand', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MissingData', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoMemory', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InternalError', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnknownVariable', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidData', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Timeout', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=209,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)

_TRACECMD_SUBCMD = _descriptor.EnumDescriptor(
  name='Subcmd',
  full_name='TraceCmd.Subcmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Flush', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Download', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Start', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetVarId', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SetVarId', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetPeriod', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SetPeriod', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CountSamples', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=400,
  serialized_end=520,
)
_sym_db.RegisterEnumDescriptor(_TRACECMD_SUBCMD)

_VARACCESS_SUBCMD = _descriptor.EnumDescriptor(
  name='Subcmd',
  full_name='VarAccess.Subcmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GetInfo', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Get', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Set', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetCount', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=535,
  serialized_end=588,
)
_sym_db.RegisterEnumDescriptor(_VARACCESS_SUBCMD)

_EEPROMCMD_SUBCMD = _descriptor.EnumDescriptor(
  name='Subcmd',
  full_name='EepromCmd.Subcmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Read', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Write', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=603,
  serialized_end=632,
)
_sym_db.RegisterEnumDescriptor(_EEPROMCMD_SUBCMD)

_VAR_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Var.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Int32', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UInt32', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Float', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=641,
  serialized_end=681,
)
_sym_db.RegisterEnumDescriptor(_VAR_TYPE)

_VAR_ACCESS = _descriptor.EnumDescriptor(
  name='Access',
  full_name='Var.Access',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ReadOnly', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReadWrite', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=683,
  serialized_end=720,
)
_sym_db.RegisterEnumDescriptor(_VAR_ACCESS)

_CONTROLLERDBG_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='ControllerDbg.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Normal', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Boot', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=739,
  serialized_end=767,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLERDBG_MODE)


_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CMD_CODE,
    _CMD_SPECIALCHAR,
    _CMD_BASE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=196,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERROR_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=360,
)


_TRACECMD = _descriptor.Descriptor(
  name='TraceCmd',
  full_name='TraceCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MaxTraceVars', full_name='TraceCmd.MaxTraceVars', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRACECMD_SUBCMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=520,
)


_VARACCESS = _descriptor.Descriptor(
  name='VarAccess',
  full_name='VarAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VARACCESS_SUBCMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=588,
)


_EEPROMCMD = _descriptor.Descriptor(
  name='EepromCmd',
  full_name='EepromCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EEPROMCMD_SUBCMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=632,
)


_VAR = _descriptor.Descriptor(
  name='Var',
  full_name='Var',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VAR_TYPE,
    _VAR_ACCESS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=634,
  serialized_end=720,
)


_CONTROLLERDBG = _descriptor.Descriptor(
  name='ControllerDbg',
  full_name='ControllerDbg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLLERDBG_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=767,
)

_CMD_CODE.containing_type = _CMD
_CMD_SPECIALCHAR.containing_type = _CMD
_CMD_BASE.containing_type = _CMD
_ERROR_CODE.containing_type = _ERROR
_TRACECMD_SUBCMD.containing_type = _TRACECMD
_VARACCESS_SUBCMD.containing_type = _VARACCESS
_EEPROMCMD_SUBCMD.containing_type = _EEPROMCMD
_VAR_TYPE.containing_type = _VAR
_VAR_ACCESS.containing_type = _VAR
_CONTROLLERDBG_MODE.containing_type = _CONTROLLERDBG
DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['TraceCmd'] = _TRACECMD
DESCRIPTOR.message_types_by_name['VarAccess'] = _VARACCESS
DESCRIPTOR.message_types_by_name['EepromCmd'] = _EEPROMCMD
DESCRIPTOR.message_types_by_name['Var'] = _VAR
DESCRIPTOR.message_types_by_name['ControllerDbg'] = _CONTROLLERDBG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), dict(
  DESCRIPTOR = _CMD,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Cmd)
  ))
_sym_db.RegisterMessage(Cmd)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Error)
  ))
_sym_db.RegisterMessage(Error)

TraceCmd = _reflection.GeneratedProtocolMessageType('TraceCmd', (_message.Message,), dict(
  DESCRIPTOR = _TRACECMD,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:TraceCmd)
  ))
_sym_db.RegisterMessage(TraceCmd)

VarAccess = _reflection.GeneratedProtocolMessageType('VarAccess', (_message.Message,), dict(
  DESCRIPTOR = _VARACCESS,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:VarAccess)
  ))
_sym_db.RegisterMessage(VarAccess)

EepromCmd = _reflection.GeneratedProtocolMessageType('EepromCmd', (_message.Message,), dict(
  DESCRIPTOR = _EEPROMCMD,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:EepromCmd)
  ))
_sym_db.RegisterMessage(EepromCmd)

Var = _reflection.GeneratedProtocolMessageType('Var', (_message.Message,), dict(
  DESCRIPTOR = _VAR,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Var)
  ))
_sym_db.RegisterMessage(Var)

ControllerDbg = _reflection.GeneratedProtocolMessageType('ControllerDbg', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERDBG,
  __module__ = 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:ControllerDbg)
  ))
_sym_db.RegisterMessage(ControllerDbg)


# @@protoc_insertion_point(module_scope)
