codecov:
  token: a570973b-0fb7-4c26-867c-ce2fc9d7458e
  require_ci_to_pass: no

coverage:
  precision: 2
  range: "70...100"
  round: down
  status:
    project:
      default:
        target: auto
      controller:
        flags:
          - controller
      gui:
        flags:
          - gui
      common:
        flags:
          - common

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  after_n_builds: 3

flags:
  controller:
    paths:
      - software/controller
    carryforward: false
  gui:
    paths:
      - software/gui
    carryforward: false
  common:
    paths:
      - software/common
    carryforward: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
