repos:
- repo: https://github.com/jlebar/pre-commit-hooks
  rev: 3c53ed59c0c749b787e793a9951afb5f877c60e9
  hooks:
  - id: clang-format
    name: clang-format C++
    types: [c++]
  - id: clang-format
    name: clang-format C
    types: [c]
    exclude_types: [c++]
