language: cpp
compiler: gcc

sudo: required

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - libqt5charts5-dev

# https://docs.platformio.org/en/latest/integration/ci/travis.html#travis-ci
cache:
    directories:
        - "~/.platformio"
        # - $HOME/.cache/pre-commit
        # - $HOME/.cache/pre-commit-jlebar

install:
  - pip install -U platformio
  - platformio update
  - pip install pre-commit

# TODO: Separate jobs for GUI and controller?
script:
  # Run checks for non-GUI code
  - ./test.sh

# TODO: Disabled because $TRAVIS_BRANCH sometimes can be set incorrectly
# (https://github.com/RespiraWorks/VentilatorSoftware/issues/184)
# Pre-commit checks are only runing on changed files.
# changed_files=$(git diff --name-only $TRAVIS_BRANCH...HEAD)
# echo "Changed files: " $changed_files
# Make git think these changes are uncommitted
# git reset --soft $TRAVIS_BRANCH
# Run precommit only on the files changed in our branch since merge-base
# pre-commit run --show-diff-on-failure --files $changed_files

  # Make sure GUI builds.
  - cd gui
  - mkdir build
  - cd build
  - qmake ..
  - make
  - ./ProjectVentilatorGUI -d
  - ./ProjectVentilatorGUI -h
