language: cpp
compiler: gcc

sudo: required

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - libqt5charts5-dev
      - libqt5serialport5-dev

# https://docs.platformio.org/en/latest/integration/ci/travis.html#travis-ci
cache:
    directories:
        - "~/.platformio"
        # Temporarily commented out because of
        # https://github.com/RespiraWorks/VentilatorSoftware/pull/191
        # - $HOME/.cache/pre-commit
        # - $HOME/.cache/pre-commit-jlebar

install:
  - pip install -U platformio
  - platformio update
  - pip install pre-commit

# TODO: Separate jobs for GUI and controller?
script:
  # Run checks for non-GUI code
  - ./test.sh
  # Run Travis-only tests
  - ./travis_only_test.sh
  # Make sure GUI builds and starts up
  - ./gui/build.sh
  - ./gui/build/ProjectVentilatorGUI --startup-only
