language: cpp
compiler: gcc

sudo: required

dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - libqt5charts5-dev

#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script:
  - mkdir build
  - cd build
  - qmake ..
  - make
  - ./ProjectVentilatorGUI -d
  - ./ProjectVentilatorGUI -h
  - ./ProjectVentilatorGUI