language: cpp
compiler: gcc

sudo: required

dist: bionic
addons:
  apt:
    packages:
      - qtdeclarative5-dev
      - libqt5charts5-dev
#      - libqt5virtualkeyboard5-dev

install:
#  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

before_script:
  - mkdir build
  - cd build
  - qmake -qt=qt5 ..

script:
  - make


