language: cpp
compiler: gcc

sudo: required

dist: bionic
addons:
  apt:
    packages:
      - qt5-default
      - qtdeclarative5-dev
      - libqt5charts5-dev

before_script:
  - mkdir build
  - cd build

script:
  - qmake ..
  - make
  - ./ProjectVentilatorGUI -d./ProjectVentilatorGUI -d
  - ./ProjectVentilatorGUI -d./ProjectVentilatorGUI -h
