language: cpp
compiler: gcc

sudo: required

dist: bionic
addons:
  apt:
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5charts5-dev
      - qt5-default
      - qttools5-dev-tools
      - qttools5-dev

#install:
#  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

before_script:
  - mkdir build
  - cd build
  - which qmake
  - qmake -qt=qt5 -v

script:
  - qmake -qt=qt5 ..
  - make

