//NOTE: Please remove this line to prevent this file being overwritten by the flow generation process
//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Light and Greenhouse Modeling Library v 1.3.0
// From: VentilatorUI PreUseTest_MainViewPanelLayout
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------

import GreenHouse 1.0
import QtQuick 2.0

import "qrc:/VentilatorUI/private/"
import "qrc:/VentilatorUI/animations/"
import "qrc:/VentilatorUI/interfaces/"

PreUseTest_MainViewPanelLayout {
    id: root

    property bool fillParent: false
    x: fillParent ? 0 : 29
    y: fillParent ? 0 : 80
    width: fillParent ? (parent ? parent.width : 0) : 966
    height: fillParent ? (parent ? parent.height : 0) : 501

    inputFallthroughBlocked: true

    showAnimation: PreUseTest_MainViewPanelLayoutShowAnimation { target: root }
    hideAnimation: PreUseTest_MainViewPanelLayoutHideAnimation { target: root }
    initAction: PreUseTest_MainViewPanelLayoutInitAnimation { target: root }

    itemInterface: PreUseTest_MainViewPanelIFaceImpl {}
}
