//NOTE: Please remove this line to prevent this file being overwritten by the flow generation process
//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Light and Greenhouse Modeling Library v 1.3.0
// From: VentilatorUI TopBarPanel_Shared0Layout
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------

import GreenHouse 1.0
import QtQuick 2.0

import "qrc:/VentilatorUI/private/"
import "qrc:/VentilatorUI/animations/"
import "qrc:/VentilatorUI/interfaces/"

TopBarPanel_Shared0Layout {
    id: root

    property bool fillParent: false
    x: fillParent ? 0 : 0
    y: fillParent ? 0 : 0
    width: fillParent ? (parent ? parent.width : 0) : 1024
    height: fillParent ? (parent ? parent.height : 0) : 60

    inputFallthroughBlocked: true

    showAnimation: TopBarPanel_Shared0LayoutShowAnimation { target: root }
    hideAnimation: TopBarPanel_Shared0LayoutHideAnimation { target: root }
    initAction: TopBarPanel_Shared0LayoutInitAnimation { target: root }

    itemInterface: TopBarPanel_Shared0IFaceImpl {}
}
