/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "debug_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Cmd, Cmd, AUTO)


PB_BIND(Error, Error, AUTO)


PB_BIND(TraceCmd, TraceCmd, AUTO)


PB_BIND(VarAccess, VarAccess, AUTO)


PB_BIND(EepromCmd, EepromCmd, AUTO)


PB_BIND(Var, Var, AUTO)


PB_BIND(ControllerDbg, ControllerDbg, AUTO)













