/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "debug_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(debug_protocol_Command, debug_protocol_Command, AUTO)


PB_BIND(debug_protocol_Error, debug_protocol_Error, AUTO)


PB_BIND(debug_protocol_Trace, debug_protocol_Trace, AUTO)


PB_BIND(debug_protocol_VariableAccess, debug_protocol_VariableAccess, AUTO)


PB_BIND(debug_protocol_EepromCommand, debug_protocol_EepromCommand, AUTO)








