# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='debug_protocol.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64\x65\x62ug_protocol.proto\"g\n\x07\x43ommand\"\\\n\x04\x43ode\x12\x08\n\x04Mode\x10\x00\x12\x08\n\x04Peek\x10\x01\x12\x08\n\x04Poke\x10\x02\x12\x0b\n\x07\x43onsole\x10\x03\x12\x0c\n\x08Variable\x10\x04\x12\t\n\x05Trace\x10\x05\x12\x10\n\x0c\x45\x65promAccess\x10\x06\"\xa1\x01\n\x05\x45rror\"\x97\x01\n\x04\x43ode\x12\x08\n\x04None\x10\x00\x12\x0c\n\x08\x43rcError\x10\x01\x12\x12\n\x0eUnknownCommand\x10\x02\x12\x0f\n\x0bMissingData\x10\x03\x12\x0c\n\x08NoMemory\x10\x04\x12\x11\n\rInternalError\x10\x05\x12\x13\n\x0fUnknownVariable\x10\x06\x12\x0f\n\x0bInvalidData\x10\x07\x12\x0b\n\x07Timeout\x10\x08\"\x85\x01\n\x05Trace\"|\n\nSubcommand\x12\t\n\x05\x46lush\x10\x00\x12\x0c\n\x08\x44ownload\x10\x01\x12\t\n\x05Start\x10\x02\x12\x0c\n\x08GetVarId\x10\x03\x12\x0c\n\x08SetVarId\x10\x04\x12\r\n\tGetPeriod\x10\x05\x12\r\n\tSetPeriod\x10\x06\x12\x10\n\x0c\x43ountSamples\x10\x07\"=\n\x0eVariableAccess\"+\n\nSubcommand\x12\x0b\n\x07GetInfo\x10\x00\x12\x07\n\x03Get\x10\x01\x12\x07\n\x03Set\x10\x02\"2\n\rEepromCommand\"!\n\nSubcommand\x12\x08\n\x04Read\x10\x00\x12\t\n\x05Write\x10\x01'
)



_COMMAND_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Command.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Mode', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Peek', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Poke', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Console', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Variable', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Trace', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EepromAccess', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=35,
  serialized_end=127,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_CODE)

_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='Error.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CrcError', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UnknownCommand', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MissingData', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NoMemory', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InternalError', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UnknownVariable', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InvalidData', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Timeout', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)

_TRACE_SUBCOMMAND = _descriptor.EnumDescriptor(
  name='Subcommand',
  full_name='Trace.Subcommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Flush', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Download', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Start', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GetVarId', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SetVarId', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GetPeriod', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SetPeriod', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CountSamples', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=303,
  serialized_end=427,
)
_sym_db.RegisterEnumDescriptor(_TRACE_SUBCOMMAND)

_VARIABLEACCESS_SUBCOMMAND = _descriptor.EnumDescriptor(
  name='Subcommand',
  full_name='VariableAccess.Subcommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GetInfo', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Get', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Set', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=447,
  serialized_end=490,
)
_sym_db.RegisterEnumDescriptor(_VARIABLEACCESS_SUBCOMMAND)

_EEPROMCOMMAND_SUBCOMMAND = _descriptor.EnumDescriptor(
  name='Subcommand',
  full_name='EepromCommand.Subcommand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Read', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Write', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=509,
  serialized_end=542,
)
_sym_db.RegisterEnumDescriptor(_EEPROMCOMMAND_SUBCOMMAND)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=127,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERROR_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=291,
)


_TRACE = _descriptor.Descriptor(
  name='Trace',
  full_name='Trace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRACE_SUBCOMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=427,
)


_VARIABLEACCESS = _descriptor.Descriptor(
  name='VariableAccess',
  full_name='VariableAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VARIABLEACCESS_SUBCOMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=490,
)


_EEPROMCOMMAND = _descriptor.Descriptor(
  name='EepromCommand',
  full_name='EepromCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EEPROMCOMMAND_SUBCOMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=542,
)

_COMMAND_CODE.containing_type = _COMMAND
_ERROR_CODE.containing_type = _ERROR
_TRACE_SUBCOMMAND.containing_type = _TRACE
_VARIABLEACCESS_SUBCOMMAND.containing_type = _VARIABLEACCESS
_EEPROMCOMMAND_SUBCOMMAND.containing_type = _EEPROMCOMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['Trace'] = _TRACE
DESCRIPTOR.message_types_by_name['VariableAccess'] = _VARIABLEACCESS
DESCRIPTOR.message_types_by_name['EepromCommand'] = _EEPROMCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Error)
  })
_sym_db.RegisterMessage(Error)

Trace = _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), {
  'DESCRIPTOR' : _TRACE,
  '__module__' : 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Trace)
  })
_sym_db.RegisterMessage(Trace)

VariableAccess = _reflection.GeneratedProtocolMessageType('VariableAccess', (_message.Message,), {
  'DESCRIPTOR' : _VARIABLEACCESS,
  '__module__' : 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:VariableAccess)
  })
_sym_db.RegisterMessage(VariableAccess)

EepromCommand = _reflection.GeneratedProtocolMessageType('EepromCommand', (_message.Message,), {
  'DESCRIPTOR' : _EEPROMCOMMAND,
  '__module__' : 'debug_protocol_pb2'
  # @@protoc_insertion_point(class_scope:EepromCommand)
  })
_sym_db.RegisterMessage(EepromCommand)


# @@protoc_insertion_point(module_scope)
