/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "debug_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)


PB_BIND(Error, Error, AUTO)


PB_BIND(Trace, Trace, AUTO)


PB_BIND(VariableAccess, VariableAccess, AUTO)


PB_BIND(EepromCommand, EepromCommand, AUTO)


PB_BIND(Var, Var, AUTO)










