/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_DEBUG_PROTOCOL_PB_H_INCLUDED
#define PB_DEBUG_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Command_Code { 
    Command_Code_Mode = 0, 
    Command_Code_Peek = 1, 
    Command_Code_Poke = 2, 
    Command_Code_Console = 3, 
    Command_Code_Variable = 4, 
    Command_Code_Trace = 5, 
    Command_Code_EepromAccess = 6 
} Command_Code;

typedef enum _Error_Code { 
    Error_Code_None = 0, 
    Error_Code_CrcError = 1, 
    Error_Code_UnknownCommand = 2, 
    Error_Code_MissingData = 3, 
    Error_Code_NoMemory = 4, 
    Error_Code_InternalError = 5, 
    Error_Code_UnknownVariable = 6, 
    Error_Code_InvalidData = 7, 
    Error_Code_Timeout = 8 
} Error_Code;

typedef enum _Trace_Subcommand { 
    Trace_Subcommand_Flush = 0, 
    Trace_Subcommand_Download = 1, 
    Trace_Subcommand_Start = 2, 
    Trace_Subcommand_GetVarId = 3, 
    Trace_Subcommand_SetVarId = 4, 
    Trace_Subcommand_GetPeriod = 5, 
    Trace_Subcommand_SetPeriod = 6, 
    Trace_Subcommand_CountSamples = 7 
} Trace_Subcommand;

typedef enum _VariableAccess_Subcommand { 
    VariableAccess_Subcommand_GetInfo = 0, 
    VariableAccess_Subcommand_Get = 1, 
    VariableAccess_Subcommand_Set = 2 
} VariableAccess_Subcommand;

typedef enum _EepromCommand_Subcommand { 
    EepromCommand_Subcommand_Read = 0, 
    EepromCommand_Subcommand_Write = 1 
} EepromCommand_Subcommand;

/* Struct definitions */
typedef struct _Command { 
    char dummy_field;
} Command;

typedef struct _EepromCommand { 
    char dummy_field;
} EepromCommand;

typedef struct _Error { 
    char dummy_field;
} Error;

typedef struct _Trace { 
    char dummy_field;
} Trace;

typedef struct _VariableAccess { 
    char dummy_field;
} VariableAccess;


/* Helper constants for enums */
#define _Command_Code_MIN Command_Code_Mode
#define _Command_Code_MAX Command_Code_EepromAccess
#define _Command_Code_ARRAYSIZE ((Command_Code)(Command_Code_EepromAccess+1))

#define _Error_Code_MIN Error_Code_None
#define _Error_Code_MAX Error_Code_Timeout
#define _Error_Code_ARRAYSIZE ((Error_Code)(Error_Code_Timeout+1))

#define _Trace_Subcommand_MIN Trace_Subcommand_Flush
#define _Trace_Subcommand_MAX Trace_Subcommand_CountSamples
#define _Trace_Subcommand_ARRAYSIZE ((Trace_Subcommand)(Trace_Subcommand_CountSamples+1))

#define _VariableAccess_Subcommand_MIN VariableAccess_Subcommand_GetInfo
#define _VariableAccess_Subcommand_MAX VariableAccess_Subcommand_Set
#define _VariableAccess_Subcommand_ARRAYSIZE ((VariableAccess_Subcommand)(VariableAccess_Subcommand_Set+1))

#define _EepromCommand_Subcommand_MIN EepromCommand_Subcommand_Read
#define _EepromCommand_Subcommand_MAX EepromCommand_Subcommand_Write
#define _EepromCommand_Subcommand_ARRAYSIZE ((EepromCommand_Subcommand)(EepromCommand_Subcommand_Write+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Command_init_default                     {0}
#define Error_init_default                       {0}
#define Trace_init_default                       {0}
#define VariableAccess_init_default              {0}
#define EepromCommand_init_default               {0}
#define Command_init_zero                        {0}
#define Error_init_zero                          {0}
#define Trace_init_zero                          {0}
#define VariableAccess_init_zero                 {0}
#define EepromCommand_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define Command_FIELDLIST(X, a) \

#define Command_CALLBACK NULL
#define Command_DEFAULT NULL

#define Error_FIELDLIST(X, a) \

#define Error_CALLBACK NULL
#define Error_DEFAULT NULL

#define Trace_FIELDLIST(X, a) \

#define Trace_CALLBACK NULL
#define Trace_DEFAULT NULL

#define VariableAccess_FIELDLIST(X, a) \

#define VariableAccess_CALLBACK NULL
#define VariableAccess_DEFAULT NULL

#define EepromCommand_FIELDLIST(X, a) \

#define EepromCommand_CALLBACK NULL
#define EepromCommand_DEFAULT NULL

extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t Error_msg;
extern const pb_msgdesc_t Trace_msg;
extern const pb_msgdesc_t VariableAccess_msg;
extern const pb_msgdesc_t EepromCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Command_fields &Command_msg
#define Error_fields &Error_msg
#define Trace_fields &Trace_msg
#define VariableAccess_fields &VariableAccess_msg
#define EepromCommand_fields &EepromCommand_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             0
#define EepromCommand_size                       0
#define Error_size                               0
#define Trace_size                               0
#define VariableAccess_size                      0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
