---
- name: Install Docker
  hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Update apt packages
    apt:
      update_cache: "yes"
      force_apt_get: "yes"

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg
      state: present
    tags:
      - docker

  - name: Update apt packages
    apt:
      update_cache: "yes"
      force_apt_get: "yes"

  - name: Set up Debian to use legacy iptables
    shell: update-alternatives --set iptables /usr/sbin/iptables-legacy

  - name: Set up Debian to use legacy ip6tables
    shell: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

  - name: Download Docker convenience script
    shell: curl -fsSL https://get.docker.com -o get-docker.sh
    tags:
      - docker

  - name: Run Docker convenience script
    shell: sh get-docker.sh
    tags:
      - docker

  - name: Adding user pi to docker group
    shell: usermod -aG docker pi
    tags:
      - docker

  - name: Install Debian menu for Openbox
    apt:
      pkg:
        - pulseaudio
        - lightdm
        - openbox
        - menu

  - name: Create config directory
    file:
      path: /home/pi/.config
      state: directory
      owner: pi
      group: pi

  - name: Create user systemd default.target.wants directory
    file:
      path: /home/pi/.config/systemd/user/default.target.wants/
      state: directory
      owner: pi
      group: pi

  - name: Create user systemd socket.target.wants directory
    file:
      path: /home/pi/.config/systemd/user/socket.target.wants/
      state: directory
      owner: pi
      group: pi

  - name: Create user systemd default.target.wants directory
    file:
      src: /usr/lib/systemd/user/pulseaudio.service
      dest: /home/pi/.config/systemd/user/default.target.wants/pulseaudio.service
      state: link
      owner: pi
      group: pi

  - name: Create user systemd socket.target.wants directory
    file:
      src: /usr/lib/systemd/user/pulseaudio.socket
      dest: /home/pi/.config/systemd/user/sockets.target.wants/pulseaudio.socket
      state: directory
      owner: pi
      group: pi

  - name: Creates /lib/systemd/user directory
    file:
      path: /lib/systemd/user
      state: directory

  - name: Add pulseaudio socket systemd config
    copy:
      src: pulseaudio.socket
      dest: /lib/systemd/user/pulseaudio.socket
      mode: '0644'
      owner: pi
      group: pi

  - name: Add pulseaudio service systemd config
    copy:
      src: pulseaudio.service
      dest: /lib/systemd/user/pulseaudio.service
      mode: '0644'
      owner: pi
      group: pi

  - name: Set pi user's .xsession
    lineinfile:
      dest: /home/pi/.xsession
      line: 'exec openbox-session'
      create: yes

  - name: Configure lightdm (enables auto-login)
    copy:
      src: lightdm.conf
      dest: /etc/lightdm/lightdm.conf
      mode: '0644'
      force: yes

  - name: Cache most recent gui docker image from dockerhub
    shell: docker pull respiraworks/gui
    tags:
      - docker

  - name: Copy openbox autostart folder from root to pi
    shell: cp -r /etc/xdg/openbox /home/pi/.config/

  - name: Disable first-time boot setup wizard
    shell: rm -f /etc/xdg/autostart/piwiz.desktop

  - name: Add script to spin up gui docker instance on boot
    lineinfile:
      dest: /home/pi/.config/openbox/autostart
      line: 'docker run --name=gui --privileged -d --restart unless-stopped --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --env="DISPLAY" --net=host -i -t respiraworks/gui /gui/build/app/ProjectVentilatorGUI --serial-port /dev/ttyS0 &'
