//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Light and Greenhouse Modeling Library v 1.3.0
// From: VentilatorUI SurfaceController Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#pragma once

#include "../appcore_global.h"
#include <QObject>
#include <greenhousecontext.h>

namespace VentilatorUI {
///
/// \brief The SurfaceController class is
///
class APPCORE_EXPORT SurfaceController : public QObject
{
    Q_OBJECT
    Q_DISABLE_COPY(SurfaceController)

public:
    explicit SurfaceController(QObject *parent = nullptr);
    ~SurfaceController() override = default;
    SurfaceController(SurfaceController &&) = delete;
    SurfaceController &operator=(SurfaceController &&) = delete;

public slots:

signals:
    ///
    /// \brief showPopups
    ///
    void showPopups();

    ///
    /// \brief hidePopups
    ///
    void hidePopups();

    ///
    /// \brief showMenus
    ///
    void showMenus();

    ///
    /// \brief hideMenus
    ///
    void hideMenus();

    ///
    /// \brief surfaceMenusBack
    ///
    void surfaceMenusBack();

    ///
    /// \brief showBackground
    ///
    void showBackground();

    ///
    /// \brief hideBackground
    ///
    void hideBackground();

    ///
    /// \brief showMainViewPanel
    ///
    void showMainViewPanel();

    ///
    /// \brief hideMainViewPanel
    ///
    void hideMainViewPanel();

    ///
    /// \brief showTopBarPanel
    ///
    void showTopBarPanel();

    ///
    /// \brief hideTopBarPanel
    ///
    void hideTopBarPanel();

    ///
    /// \brief surfaceBackgroundMoveToBackground_Shared0
    ///
    void surfaceBackgroundMoveToBackground_Shared0();

    ///
    /// \brief surfaceMainViewPanelMoveToPreUseTest_MainViewPanel
    ///
    void surfaceMainViewPanelMoveToPreUseTest_MainViewPanel();

    ///
    /// \brief surfaceTopBarPanelMoveToTopBarPanel_Shared0
    ///
    void surfaceTopBarPanelMoveToTopBarPanel_Shared0();
};
}
