//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Light and Greenhouse Modeling Library v 1.3.0
// From: VentilatorUI SurfaceController Interface
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
#include "surfacecontroller.hpp"
#include <QDebug>

namespace VentilatorUI {
SurfaceController::SurfaceController(QObject *parent)
  : QObject(parent)
{
}
}
