/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "network_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)

PB_BIND(GuiAck, GuiAck, AUTO)

PB_BIND(ControllerStatus, ControllerStatus, AUTO)

PB_BIND(ControllerIdentification, ControllerIdentification, AUTO)

PB_BIND(ControlerAlarm, ControlerAlarm, AUTO)

PB_BIND(ControllerValue, ControllerValue, AUTO)

PB_BIND(ControllerData, ControllerData, AUTO)

PB_BIND(Packet, Packet, AUTO)
