//NOTE: Please remove this line to prevent this file being overwritten by the flow generation process
//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Light and Greenhouse Modeling Library v 1.3.0
// From: VentilatorUI Background_Shared0Layout Init Animation
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------

import QtQuick 2.0

SequentialAnimation {
    id: root

    property Item target

    ScriptAction {
        script: {

        }
    }

    ScriptAction {
        script: {

        }
    }

    onStopped: {
    }
}
