# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/generated_libs/network_protocol/network_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/generated_libs/network_protocol/network_protocol.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n=common/generated_libs/network_protocol/network_protocol.proto\x1a\x0cnanopb.proto\"h\n\tGuiStatus\x12\x11\n\tuptime_ms\x18\x01 \x02(\x04\x12#\n\x0e\x64\x65sired_params\x18\x02 \x02(\x0b\x32\x0b.VentParams\x12#\n\x0c\x61\x63ked_alarms\x18\x03 \x03(\x0b\x32\x06.AlarmB\x05\x92?\x02\x10\x04\"\x9d\x01\n\x10\x43ontrollerStatus\x12\x11\n\tuptime_ms\x18\x01 \x02(\x04\x12\"\n\ractive_params\x18\x02 \x02(\x0b\x32\x0b.VentParams\x12(\n\x0fsensor_readings\x18\x03 \x02(\x0b\x32\x0f.SensorReadings\x12(\n\x11\x63ontroller_alarms\x18\x04 \x03(\x0b\x32\x06.AlarmB\x05\x92?\x02\x10\x04\"\x96\x03\n\nVentParams\x12\x17\n\x04mode\x18\x01 \x02(\x0e\x32\t.VentMode\x12\x1e\n\x16percent_inspiratory_o2\x18\x02 \x02(\r\x12\x13\n\x0bpeep_cm_h2o\x18\x03 \x02(\r\x12\x17\n\x0f\x62reaths_per_min\x18\x04 \x02(\r\x12\x12\n\npip_cm_h2o\x18\x05 \x02(\r\x12$\n\x1cinspiratory_expiratory_ratio\x18\x06 \x02(\x02\x12\x14\n\x0crise_time_ms\x18\x07 \x02(\r\x12\"\n\x1ainspiratory_trigger_cm_h2o\x18\x08 \x02(\r\x12%\n\x1d\x65xpiratory_trigger_ml_per_min\x18\t \x02(\r\x12 \n\x18\x61larm_lo_tidal_volume_ml\x18\n \x02(\r\x12 \n\x18\x61larm_hi_tidal_volume_ml\x18\x0b \x02(\r\x12 \n\x18\x61larm_lo_breaths_per_min\x18\x0c \x02(\r\x12 \n\x18\x61larm_hi_breaths_per_min\x18\r \x02(\r\"U\n\x0eSensorReadings\x12\x17\n\x0fpressure_cm_h2o\x18\x01 \x02(\x02\x12\x11\n\tvolume_ml\x18\x02 \x02(\x02\x12\x17\n\x0f\x66low_ml_per_min\x18\x03 \x02(\x02\"5\n\x05\x41larm\x12\x12\n\nstart_time\x18\x01 \x02(\x04\x12\x18\n\x04kind\x18\x02 \x02(\x0e\x32\n.AlarmKind*T\n\x08VentMode\x12\x07\n\x03OFF\x10\x00\x12\x14\n\x10PRESSURE_CONTROL\x10\x01\x12\x13\n\x0fPRESSURE_ASSIST\x10\x02\x12\x14\n\x10PRESSURE_SUPPORT\x10\x03*}\n\tAlarmKind\x12\x1c\n\x18RESPIRATORY_RATE_TOO_LOW\x10\x01\x12\x1d\n\x19RESPIRATORY_RATE_TOO_HIGH\x10\x02\x12\x18\n\x14TIDAL_VOLUME_TOO_LOW\x10\x03\x12\x19\n\x15TIDAL_VOLUME_TOO_HIGH\x10\x04')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_VENTMODE = _descriptor.EnumDescriptor(
  name='VentMode',
  full_name='VentMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESSURE_CONTROL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESSURE_ASSIST', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESSURE_SUPPORT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=896,
  serialized_end=980,
)
_sym_db.RegisterEnumDescriptor(_VENTMODE)

VentMode = enum_type_wrapper.EnumTypeWrapper(_VENTMODE)
_ALARMKIND = _descriptor.EnumDescriptor(
  name='AlarmKind',
  full_name='AlarmKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESPIRATORY_RATE_TOO_LOW', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPIRATORY_RATE_TOO_HIGH', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIDAL_VOLUME_TOO_LOW', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIDAL_VOLUME_TOO_HIGH', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=982,
  serialized_end=1107,
)
_sym_db.RegisterEnumDescriptor(_ALARMKIND)

AlarmKind = enum_type_wrapper.EnumTypeWrapper(_ALARMKIND)
OFF = 0
PRESSURE_CONTROL = 1
PRESSURE_ASSIST = 2
PRESSURE_SUPPORT = 3
RESPIRATORY_RATE_TOO_LOW = 1
RESPIRATORY_RATE_TOO_HIGH = 2
TIDAL_VOLUME_TOO_LOW = 3
TIDAL_VOLUME_TOO_HIGH = 4



_GUISTATUS = _descriptor.Descriptor(
  name='GuiStatus',
  full_name='GuiStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uptime_ms', full_name='GuiStatus.uptime_ms', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desired_params', full_name='GuiStatus.desired_params', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acked_alarms', full_name='GuiStatus.acked_alarms', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020\004'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=183,
)


_CONTROLLERSTATUS = _descriptor.Descriptor(
  name='ControllerStatus',
  full_name='ControllerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uptime_ms', full_name='ControllerStatus.uptime_ms', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_params', full_name='ControllerStatus.active_params', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor_readings', full_name='ControllerStatus.sensor_readings', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='controller_alarms', full_name='ControllerStatus.controller_alarms', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020\004'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=343,
)


_VENTPARAMS = _descriptor.Descriptor(
  name='VentParams',
  full_name='VentParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='VentParams.mode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='percent_inspiratory_o2', full_name='VentParams.percent_inspiratory_o2', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peep_cm_h2o', full_name='VentParams.peep_cm_h2o', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='breaths_per_min', full_name='VentParams.breaths_per_min', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pip_cm_h2o', full_name='VentParams.pip_cm_h2o', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inspiratory_expiratory_ratio', full_name='VentParams.inspiratory_expiratory_ratio', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rise_time_ms', full_name='VentParams.rise_time_ms', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inspiratory_trigger_cm_h2o', full_name='VentParams.inspiratory_trigger_cm_h2o', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiratory_trigger_ml_per_min', full_name='VentParams.expiratory_trigger_ml_per_min', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_lo_tidal_volume_ml', full_name='VentParams.alarm_lo_tidal_volume_ml', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_hi_tidal_volume_ml', full_name='VentParams.alarm_hi_tidal_volume_ml', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_lo_breaths_per_min', full_name='VentParams.alarm_lo_breaths_per_min', index=11,
      number=12, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_hi_breaths_per_min', full_name='VentParams.alarm_hi_breaths_per_min', index=12,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=752,
)


_SENSORREADINGS = _descriptor.Descriptor(
  name='SensorReadings',
  full_name='SensorReadings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure_cm_h2o', full_name='SensorReadings.pressure_cm_h2o', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume_ml', full_name='SensorReadings.volume_ml', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flow_ml_per_min', full_name='SensorReadings.flow_ml_per_min', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=754,
  serialized_end=839,
)


_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='Alarm.start_time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='Alarm.kind', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=894,
)

_GUISTATUS.fields_by_name['desired_params'].message_type = _VENTPARAMS
_GUISTATUS.fields_by_name['acked_alarms'].message_type = _ALARM
_CONTROLLERSTATUS.fields_by_name['active_params'].message_type = _VENTPARAMS
_CONTROLLERSTATUS.fields_by_name['sensor_readings'].message_type = _SENSORREADINGS
_CONTROLLERSTATUS.fields_by_name['controller_alarms'].message_type = _ALARM
_VENTPARAMS.fields_by_name['mode'].enum_type = _VENTMODE
_ALARM.fields_by_name['kind'].enum_type = _ALARMKIND
DESCRIPTOR.message_types_by_name['GuiStatus'] = _GUISTATUS
DESCRIPTOR.message_types_by_name['ControllerStatus'] = _CONTROLLERSTATUS
DESCRIPTOR.message_types_by_name['VentParams'] = _VENTPARAMS
DESCRIPTOR.message_types_by_name['SensorReadings'] = _SENSORREADINGS
DESCRIPTOR.message_types_by_name['Alarm'] = _ALARM
DESCRIPTOR.enum_types_by_name['VentMode'] = _VENTMODE
DESCRIPTOR.enum_types_by_name['AlarmKind'] = _ALARMKIND

GuiStatus = _reflection.GeneratedProtocolMessageType('GuiStatus', (_message.Message,), dict(
  DESCRIPTOR = _GUISTATUS,
  __module__ = 'common.generated_libs.network_protocol.network_protocol_pb2'
  # @@protoc_insertion_point(class_scope:GuiStatus)
  ))
_sym_db.RegisterMessage(GuiStatus)

ControllerStatus = _reflection.GeneratedProtocolMessageType('ControllerStatus', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERSTATUS,
  __module__ = 'common.generated_libs.network_protocol.network_protocol_pb2'
  # @@protoc_insertion_point(class_scope:ControllerStatus)
  ))
_sym_db.RegisterMessage(ControllerStatus)

VentParams = _reflection.GeneratedProtocolMessageType('VentParams', (_message.Message,), dict(
  DESCRIPTOR = _VENTPARAMS,
  __module__ = 'common.generated_libs.network_protocol.network_protocol_pb2'
  # @@protoc_insertion_point(class_scope:VentParams)
  ))
_sym_db.RegisterMessage(VentParams)

SensorReadings = _reflection.GeneratedProtocolMessageType('SensorReadings', (_message.Message,), dict(
  DESCRIPTOR = _SENSORREADINGS,
  __module__ = 'common.generated_libs.network_protocol.network_protocol_pb2'
  # @@protoc_insertion_point(class_scope:SensorReadings)
  ))
_sym_db.RegisterMessage(SensorReadings)

Alarm = _reflection.GeneratedProtocolMessageType('Alarm', (_message.Message,), dict(
  DESCRIPTOR = _ALARM,
  __module__ = 'common.generated_libs.network_protocol.network_protocol_pb2'
  # @@protoc_insertion_point(class_scope:Alarm)
  ))
_sym_db.RegisterMessage(Alarm)


_GUISTATUS.fields_by_name['acked_alarms'].has_options = True
_GUISTATUS.fields_by_name['acked_alarms']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020\004'))
_CONTROLLERSTATUS.fields_by_name['controller_alarms'].has_options = True
_CONTROLLERSTATUS.fields_by_name['controller_alarms']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\222?\002\020\004'))
# @@protoc_insertion_point(module_scope)
