/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "network_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GuiStatus, GuiStatus, AUTO)


PB_BIND(ControllerStatus, ControllerStatus, AUTO)


PB_BIND(VentParams, VentParams, AUTO)


PB_BIND(SensorReadings, SensorReadings, AUTO)


PB_BIND(Alarm, Alarm, AUTO)
