# Copyright 2023, RespiraWorks
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#FROM ubuntu:22.04
#FROM python
FROM ubuntu

USER root

#RUN rm -rf /var/lib/apt/lists/*

# ubuntu:latest does not have sudo
# fetch it and install it
RUN apt-get update
RUN apt-get install -y \
    sudo
RUN apt-get install -y \
    python3
RUN python3 -m pip install --upgrade pip

# Create new user `jenkins` and disable
# password and gecos for later
# --gecos explained well here:
# https://askubuntu.com/a/1195288/635348
RUN adduser --disabled-password --gecos '' jenkins

#  Add new user jenkins to sudo group
RUN adduser jenkins sudo
#RUN usermod -a -G sudo jenkins

# Ensure sudo group users are not
# asked for a password when using
# sudo command by ammending sudoers file
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER jenkins
WORKDIR /home/jenkins

ENTRYPOINT ["tail"]

CMD ["-f","/dev/null"]
