//--------------------------------------------------------------------------------------------------
// Generated using GreenHouse Light and Greenhouse Modeling Library v 1.3.0
// From: VentilatorUI
// Please do not edit this file as it will be overwritten the next time the application flow is
// regenerated.
//--------------------------------------------------------------------------------------------------
import QtQuick 2.0
import GreenHouse.Theming 1.0

GreenHouseTheme {
    id: root
    themeBaseDir: "qrc:/Themes/VentilatorUI/DefaultTheme"
}
